'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { runtime } = require('./helpers/v2-runtime');
const { seedInventory } = require('./helpers/inventory-fixture');
const ADMIN='000000000001', CLIENT='000000000002';
const products = () => [['BLANCO','Equipo','16 GB','blanco',2,100,'Ficha blanco'],['PLATA','Equipo','32 GB','plateado',1,50,'Ficha plata']];
const order = (multi=false, id='LU0001') => ({estado:'confirmado',confirmado:true,datosCliente:{nombre:'Persona sintética',cedula:'0012345678',provincia:'P',ciudad:'C'},historial:[],pedido:{id_chat:'CH'+id.slice(2).padStart(6,'0'),id,estado:'confirmado',guia:null,lineas:[{id_producto:'BLANCO',producto:'Equipo',capacidad:'16 GB',color:'blanco',cantidad:2,precio_unitario:100},...(multi?[{id_producto:'PLATA',producto:'Equipo',capacidad:'32 GB',color:'plateado',cantidad:1,precio_unitario:50}]:[])]}});
async function fixture({multi=false, stock=products()}={}) {
  const e=runtime();await e.inventoryReady;await seedInventory(e.sheets,stock);await e.seed(order(multi));
  const batches=[],update=e.sheets.spreadsheets.batchUpdate;
  e.sheets.spreadsheets.batchUpdate=async args=>{batches.push(structuredClone(args));return update(args);};
  const get=e.sheets.spreadsheets.values.get;
  // Simulated Sheets formula: backend only records sale rows; this test-owned reader recalculates availability.
  e.sheets.spreadsheets.values.get=async args=>{
    const result=await get(args);
    if(args.range === "'PAGINA DE STOCK'!A3:G") {
      const rows=(await get({range:"'REGISTRO DE VENTAS'!A5:W"})).data.values;
      result.data.values=result.data.values.map(row=>{const copy=[...row];copy[4]-=rows.filter(r=>r[14]===row[0]&&['enviado','en agencia','retirado','cancelado','pagado'].includes(r[5])).reduce((sum,r)=>sum+Number(r[18]),0);return copy;});
    }
    return result;
  };
  return Object.assign(e,{batches,guia:(text='GUIA (CH000001) (G1)',opts={})=>e.message(text,{from:ADMIN,...opts}),clients:()=>e.sent.filter(m=>m.to===CLIENT),sales:async()=> (await get({range:"'REGISTRO DE VENTAS'!A5:W"})).data.values.filter(r=>r[2])});
}
test('GUIA mono-línea con stock exacto registra venta, guía, takeover y aviso',async()=>{const e=await fixture();assert.equal(await e.guia(),200);const c=await e.load(),rows=await e.sales();assert.equal(rows.length,1);assert.equal(rows[0][5],'enviado');assert.equal(rows[0][18],2);assert.equal(c.pedido.estado,'enviado');assert.equal(c.pedido.guia,'G1');assert.equal(c.human_takeover,true);assert.equal(e.clients().length,0);await e.message('hola');assert.equal(e.clients().length,0);assert.equal(e.calls.length,0);});
test('GUIA multilínea mantiene cantidad e ID separados y fórmulas intactas',async()=>{const e=await fixture({multi:true});const before=(await e.sheets.spreadsheets.values.get({range:"'REGISTRO DE VENTAS'!A5:W"})).data.values;await e.guia();const rows=await e.sales();assert.equal(rows.length,2);assert.deepEqual(rows.map(r=>[r[14],r[18]]),[['BLANCO',2],['PLATA',1]]);for(let i=0;i<2;i++)for(const col of [15,16,17,19,20,22])assert.equal(rows[i][col],before[i][col]);assert.equal(e.batches.length,1);});
test('GUIA multilínea insuficiente: cero filas, pedido aún confirmado y solo alerta admin',async()=>{const p=products();p[1][4]=0;const e=await fixture({multi:true,stock:p});await e.guia();assert.equal((await e.sales()).length,0);const c=await e.load();assert.equal(c.pedido.estado,'confirmado');assert.equal(c.pedido.guia,null);assert.equal(c.human_takeover,true);assert.equal(e.clients().length,0);assert.equal(e.sent.filter(m=>m.to===ADMIN).length,1);assert.equal(e.batches.length,0);});
test('misma GUIA repetida no duplica filas ni notificación',async()=>{const e=await fixture();await e.guia();await e.guia();assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);assert.equal(e.batches.length,1);});
test('mismo pedido con otra guía conserva la original y alerta humano',async()=>{const e=await fixture();await e.guia();await e.guia('GUIA (CH000001) (G2)');assert.equal((await e.load()).pedido.guia,'G1');assert.equal((await e.sales()).length,1);assert.equal((await e.sales())[0][4],'G1');assert.equal(e.clients().length,0);assert.ok(e.sent.some(m=>m.to===ADMIN&&m.text.body.includes('GUIA_CONFLICTIVA')));});
test('respuesta de Sheets perdida después de escribir se recupera sin segunda venta',async()=>{const e=await fixture(),write=e.sheets.spreadsheets.batchUpdate;let once=true;e.sheets.spreadsheets.batchUpdate=async args=>{await write(args);if(once){once=false;throw Error('respuesta perdida');}};assert.equal(await e.guia(),500);assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);assert.equal(await e.guia(),200);assert.equal((await e.load()).pedido.estado,'enviado');assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);});
test('dos GUIA concurrentes del mismo pedido registran y notifican una sola vez',async()=>{const e=await fixture();await Promise.all([e.guia(),e.guia(undefined,{from:'+'+ADMIN})]);assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);});
test('pedido ya enviado sin registro V2 no se registra ni se vuelve a notificar',async()=>{const e=await fixture();const c=order();c.pedido.estado='enviado';c.pedido.guia='G1';c.estado='enviado';await e.seed(c);await e.guia();assert.equal((await e.sales()).length,0);assert.equal(e.clients().length,0);assert.equal((await e.load()).pedido.estado,'enviado');});
test('administrador no autorizado no modifica pedido ni inventario',async()=>{const e=await fixture();await e.guia(undefined,{from:CLIENT});assert.equal((await e.load()).pedido.estado,'confirmado');assert.equal((await e.sales()).length,0);assert.equal(e.sent.length,0);});
test('fallo en request intermedio del batch multilínea no deja escrituras parciales',async()=>{const e=await fixture({multi:true}),write=e.sheets.spreadsheets.batchUpdate;e.sheets.spreadsheets.batchUpdate=args=>write({...args,requestBody:{requests:[...args.requestBody.requests.slice(0,16),{updateCells:{start:{sheetId:-999,rowIndex:5,columnIndex:1},rows:[],fields:'userEnteredValue'}},...args.requestBody.requests.slice(16)]}});assert.equal(await e.guia(),500);assert.equal((await e.sales()).length,0);assert.equal((await e.load()).pedido.estado,'confirmado');assert.equal(e.clients().length,0);});
test('GUIA después de DERIVAR no registra ni reabre',async()=>{const e=await fixture();await e.message('DERIVAR (LU0001)',{from:ADMIN});await e.guia();assert.equal((await e.sales()).length,0);assert.equal((await e.load()).pedido.estado,'cerrado');assert.equal((await e.load()).closure_reason,'derivado_competencia');assert.equal(e.clients().length,0);});
for(const first of ['GUIA','DERIVAR'])test(`carrera ${first} primero no deja venta enviada y pedido derivado`,async()=>{const e=await fixture();const commands=first==='GUIA'?['GUIA (CH000001) (G1)','DERIVAR (LU0001)']:['DERIVAR (LU0001)','GUIA (CH000001) (G1)'];await Promise.all(commands.map((text,i)=>e.message(text,{from:i?'+'+ADMIN:ADMIN})));const c=await e.load(),rows=await e.sales();if(rows.length)assert.equal(c.pedido.estado,'enviado');else assert.equal(c.pedido.estado,'cerrado');assert.ok(!(rows.length&&c.closure_reason==='derivado_competencia'));});
test('DERIVAR no cierra una GUIA con resultado de escritura incierto',async()=>{const e=await fixture(),write=e.sheets.spreadsheets.batchUpdate;e.sheets.spreadsheets.batchUpdate=async a=>{await write(a);throw Error('timeout');};await e.guia();await e.message('DERIVAR (LU0001)',{from:ADMIN});const c=await e.load();assert.notEqual(c.pedido.estado,'cerrado');assert.notEqual(c.closure_reason,'derivado_competencia');assert.equal((await e.sales()).length,1);});
test('reinicio inmediato después de GUIA conserva deduplicación de venta y aviso',async()=>{const e=await fixture();await e.guia();const restart=runtime({sheets:e.sheets});await restart.message('GUIA (CH000001) (G1)',{from:ADMIN});await restart.api.revisarSeguimientos();assert.equal((await e.sales()).length,1);assert.equal(restart.sent.length,0);assert.equal((await restart.load()).human_takeover,true);});
test('reinicio entre escritura de venta y persistencia de pedido recupera el pedido',async()=>{const e=await fixture(),update=e.sheets.spreadsheets.values.update;let fail=true;e.sheets.spreadsheets.values.update=async args=>{if(fail&&args.range.startsWith('MEMORIA')&&JSON.parse(args.requestBody.values[0][1]).pedido?.sales_registered){fail=false;throw Error('fallo memoria');}return update(args);};assert.equal(await e.guia(),500);assert.equal(e.clients().length,0);const restart=runtime({sheets:e.sheets});assert.equal(await restart.message('GUIA (CH000001) (G1)',{from:ADMIN}),200);assert.equal((await restart.load()).pedido.estado,'enviado');assert.equal((await e.sales()).length,1);assert.equal(restart.sent.filter(m=>m.to===CLIENT).length,0);});
test('dos pedidos compiten por última unidad: solo uno registra',async()=>{const p=products();p[0][4]=1;const e=await fixture({stock:p});const first=order();first.pedido.lineas[0].cantidad=1;const second=order(false,'LU0002');second.pedido.lineas[0].cantidad=1;await e.seed(first);await e.seed(second,'000000000003');await Promise.all([e.guia(),e.guia('GUIA (CH000002) (G2)',{from:'+'+ADMIN})]);assert.equal((await e.sales()).length,1);const states=[(await e.load()).pedido.estado,(await e.load('000000000003')).pedido.estado];assert.deepEqual(states.sort(),['confirmado','enviado']);});
test('webhook duplicado ejecuta GUIA una sola vez',async()=>{const e=await fixture();await Promise.all([e.guia(undefined,{id:'same-webhook'}),e.guia(undefined,{id:'same-webhook'})]);assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);});
test('línea sin ID-PRODUCTO bloquea en lugar de adivinar por nombre',async()=>{const e=await fixture(),c=order();delete c.pedido.lineas[0].id_producto;await e.seed(c);await e.guia();assert.equal((await e.sales()).length,0);assert.equal(e.clients().length,0);assert.equal((await e.load()).human_takeover,true);});
test('TOMAR y GUIA conservan silencio; LIBERAR no envía guía automáticamente',async()=>{const e=await fixture();await e.message(`TOMAR (${CLIENT})`,{from:ADMIN});await e.guia();assert.equal((await e.sales()).length,1);assert.equal(e.clients().length,0);await e.message(`LIBERAR (CH000001)`,{from:ADMIN});assert.equal(e.clients().length,0);await e.guia();assert.equal(e.clients().length,0);});

test('marca de derivación bloquea GUIA aunque el estado legado sea confirmado',async()=>{const e=await fixture(),c=order();c.pedido.closure_reason='derivado_competencia';await e.seed(c);await e.guia();assert.equal((await e.sales()).length,0);assert.equal(e.clients().length,0);});
